### ISSUE TITLE
fahren

### ISSUE THREAD

**Issue by llatikay** [dlatikaynen/scorchGore#3]
ich willfahren können

**Comment by dlatikaynen** [comment]
Wenn im laufenden Spiel die Taste "a" gedrückt wird, so soll der dranseiende Spieler ein Pixel nach links rutschen.
Wenn im laufenden Spiel die Taste "d" gedrückt wird, so soll der dranseiende Spieler ein Pixel nach rechts rutschen.
Wenn ein Hindernis im Weg ist, kann nicht gefahren werden.
